# Generated by Django 4.2.7 on 2023-12-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []  # type: ignore

    operations = [
        migrations.CreateModel(
            name="Peak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Name of the peak"
                    ),
                ),
                ("alternative_names", models.TextField(blank=True, default="")),
                (
                    "unicode_name",
                    models.CharField(
                        max_length=200, verbose_name="Unicode name of the peak"
                    ),
                ),
                ("latitude", models.FloatField(null=True)),
                ("longitude", models.FloatField(null=True)),
                (
                    "elevation",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=5,
                        verbose_name="Elevation of the peak",
                    ),
                ),
                ("country_code", models.CharField(max_length=2)),
            ],
        ),
    ]
