# Generated by Django 4.2.7 on 2023-12-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peaks", "0002_region_alter_peak_options_peak_region"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="region",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="peak",
            name="country_code",
            field=models.CharField(max_length=10),
        ),
    ]
