# Generated by Django 4.2.7 on 2023-12-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peaks", "0003_alter_region_options_alter_peak_country_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peak",
            name="unicode_name",
            field=models.CharField(
                db_index=True, max_length=200, verbose_name="Unicode name of the peak"
            ),
        ),
    ]
